### ISSUE TITLE
Build de l'image telement long

### ISSUE THREAD

**Issue by Atilir** [jpwilsch/station-blanche#1]
Salut, je n'ai pas pu test ton soft car le build de l'image est tellement long !!!
J'ai une connexion à 100Mb/s et il a mis 1 jours pour télécharger uniquement des fichiers dedication dans toutes les langues possibles ! Aurais tu la possibilité de me de partagé déjà une image que tu as build ou alors de m'indiquer pourquoi le téléchargement est lent !!!

Merci

**Comment by jpwilsch** [comment]
Bonjour

La construction de l'image ne télécharge depuis les repos debian que le minimum de paquets nécessaires pour celle ci, soit moins de 500Mo, cela ne devrait pas prendre autant de temps.

Une image déjà construite est disponible dans la section releases (https://github.com/jpwilsch/station-blanche/releases) du projet : https://github.com/jpwilsch/station-blanche/releases/download/v2.0.0/station-blanche.iso

**Comment by Atilir** [comment]
Ok merci j'ai pu la tester
